import type {
  Organization,
  Barangay,
  EmergencyType,
  ResidentProfile,
  RescueUnit,
  UserProfile,
  DemoIncident,
  DemoTimelineEntry,
  AuditLog,
  Notification,
  DemoStats,
  TriageQuestion,
} from './types'

// ============================================================
// HELPERS
// ============================================================

function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 60 * 60 * 1000).toISOString()
}

function minutesAgo(m: number): string {
  return new Date(Date.now() - m * 60 * 1000).toISOString()
}

function daysAgo(d: number): string {
  return new Date(Date.now() - d * 24 * 60 * 60 * 1000).toISOString()
}

// ============================================================
// ORGANIZATION
// ============================================================

export const DEMO_ORGANIZATION: Organization = {
  id: 'org-bayani-001',
  name: 'Municipality of Bayani',
  slug: 'bayani',
  province: 'Laguna',
  region: 'CALABARZON',
  logo_url: null,
  seal_url: null,
  emergency_hotline: '049-555-1234',
  secondary_hotline: '0917-800-9119',
  email: 'rescue@bayani.gov.ph',
  website: 'https://bayani.gov.ph',
  address: 'Municipal Hall, Brgy. Poblacion, Bayani, Laguna',
  map_center: { lat: 14.1634, lng: 121.2430 },
  map_zoom: 13,
  branding: {
    primary_color: '#1d4ed8',
    secondary_color: '#dc2626',
    logo_url: null,
    favicon_url: null,
    seal_url: null,
  },
  is_active: true,
  subscription_tier: 'pro',
  created_at: daysAgo(90),
  updated_at: daysAgo(5),
}

// ============================================================
// BARANGAYS (10)
// ============================================================

export const DEMO_BARANGAYS: Barangay[] = [
  { id: 'brgy-001', municipality_id: 'mun-001', organization_id: 'org-bayani-001', name: 'Poblacion', captain_name: 'Eduardo Reyes', captain_phone: '0917-111-0001', polygon_coordinates: null, is_active: true, created_at: daysAgo(90) },
  { id: 'brgy-002', municipality_id: 'mun-001', organization_id: 'org-bayani-001', name: 'San Isidro', captain_name: 'Lourdes Bautista', captain_phone: '0917-111-0002', polygon_coordinates: null, is_active: true, created_at: daysAgo(90) },
  { id: 'brgy-003', municipality_id: 'mun-001', organization_id: 'org-bayani-001', name: 'Santo Niño', captain_name: 'Rodrigo Dela Cruz', captain_phone: '0917-111-0003', polygon_coordinates: null, is_active: true, created_at: daysAgo(90) },
  { id: 'brgy-004', municipality_id: 'mun-001', organization_id: 'org-bayani-001', name: 'San Jose', captain_name: 'Maricel Santos', captain_phone: '0917-111-0004', polygon_coordinates: null, is_active: true, created_at: daysAgo(90) },
  { id: 'brgy-005', municipality_id: 'mun-001', organization_id: 'org-bayani-001', name: 'Bagong Pag-asa', captain_name: 'Felix Macaraeg', captain_phone: '0917-111-0005', polygon_coordinates: null, is_active: true, created_at: daysAgo(90) },
  { id: 'brgy-006', municipality_id: 'mun-001', organization_id: 'org-bayani-001', name: 'Mabuhay', captain_name: 'Corazon Villanueva', captain_phone: '0917-111-0006', polygon_coordinates: null, is_active: true, created_at: daysAgo(90) },
  { id: 'brgy-007', municipality_id: 'mun-001', organization_id: 'org-bayani-001', name: 'Pag-asa', captain_name: 'Danilo Navarro', captain_phone: '0917-111-0007', polygon_coordinates: null, is_active: true, created_at: daysAgo(90) },
  { id: 'brgy-008', municipality_id: 'mun-001', organization_id: 'org-bayani-001', name: 'Maligaya', captain_name: 'Teresita Fernandez', captain_phone: '0917-111-0008', polygon_coordinates: null, is_active: true, created_at: daysAgo(90) },
  { id: 'brgy-009', municipality_id: 'mun-001', organization_id: 'org-bayani-001', name: 'Bagong Silang', captain_name: 'Armando Ramos', captain_phone: '0917-111-0009', polygon_coordinates: null, is_active: true, created_at: daysAgo(90) },
  { id: 'brgy-010', municipality_id: 'mun-001', organization_id: 'org-bayani-001', name: 'Lumang Bayan', captain_name: 'Nenita Castillo', captain_phone: '0917-111-0010', polygon_coordinates: null, is_active: true, created_at: daysAgo(90) },
]

// ============================================================
// EMERGENCY TYPES
// ============================================================

const medicalTriageQuestions: TriageQuestion[] = [
  { id: 'med-q1', question: 'Is the patient conscious?', type: 'boolean', required: true, follow_up_if_true: 'med-q2' },
  { id: 'med-q2', question: 'Is the patient breathing normally?', type: 'boolean', required: true },
  { id: 'med-q3', question: 'How many people are affected?', type: 'number', required: true },
  { id: 'med-q4', question: 'What is the nature of the emergency?', type: 'select', options: ['Cardiac arrest', 'Stroke', 'Severe bleeding', 'Trauma', 'Difficulty breathing', 'Seizure', 'Other'], required: true },
]

const fireTriageQuestions: TriageQuestion[] = [
  { id: 'fire-q1', question: 'Is anyone trapped inside?', type: 'boolean', required: true },
  { id: 'fire-q2', question: 'How many floors is the building?', type: 'number', required: false },
  { id: 'fire-q3', question: 'What type of building?', type: 'select', options: ['Residential', 'Commercial', 'Industrial', 'Government', 'Vacant'], required: true },
  { id: 'fire-q4', question: 'Is the fire spreading to adjacent structures?', type: 'boolean', required: true },
]

const floodTriageQuestions: TriageQuestion[] = [
  { id: 'flood-q1', question: 'Is anyone in immediate danger?', type: 'boolean', required: true },
  { id: 'flood-q2', question: 'Estimated water level (cm)', type: 'number', required: false },
  { id: 'flood-q3', question: 'Are children or elderly involved?', type: 'boolean', required: true },
]

const earthquakeTriageQuestions: TriageQuestion[] = [
  { id: 'eq-q1', question: 'Are there people trapped under debris?', type: 'boolean', required: true },
  { id: 'eq-q2', question: 'Are there visible structural damages?', type: 'boolean', required: true },
  { id: 'eq-q3', question: 'Estimated number of people affected', type: 'number', required: false },
  { id: 'eq-q4', question: 'Type of structure affected', type: 'select', options: ['Residential', 'Commercial', 'School', 'Government', 'Bridge/Road', 'Other'], required: true },
]

const typhoonTriageQuestions: TriageQuestion[] = [
  { id: 'typ-q1', question: 'Are there people in immediate danger?', type: 'boolean', required: true },
  { id: 'typ-q2', question: 'Type of damage', type: 'select', options: ['Roof blown off', 'Flooding', 'Fallen trees/poles', 'Landslide', 'Structural damage', 'Power lines down', 'Other'], required: true },
  { id: 'typ-q3', question: 'Are roads passable in your area?', type: 'boolean', required: false },
  { id: 'typ-q4', question: 'Estimated number of families affected', type: 'number', required: false },
]

export const DEMO_EMERGENCY_TYPES: EmergencyType[] = [
  {
    id: 'et-earthquake',
    name: 'Earthquake',
    icon: 'Activity',
    color: '#b45309',
    description: 'Earthquake damage, structural collapse, aftershock reports, trapped persons.',
    triage_questions: earthquakeTriageQuestions,
    is_active: true,
    sort_order: 0,
    organization_id: null,
    created_at: daysAgo(90),
    updated_at: daysAgo(90),
  },
  {
    id: 'et-typhoon',
    name: 'Typhoon / Storm',
    icon: 'CloudHail',
    color: '#0369a1',
    description: 'Typhoon damage, storm surge, strong winds, heavy rainfall, fallen trees.',
    triage_questions: typhoonTriageQuestions,
    is_active: true,
    sort_order: 1,
    organization_id: null,
    created_at: daysAgo(90),
    updated_at: daysAgo(90),
  },
  {
    id: 'et-medical',
    name: 'Medical Emergency',
    icon: 'Stethoscope',
    color: '#dc2626',
    description: 'Heart attacks, strokes, accidents causing injury, unconscious persons.',
    triage_questions: medicalTriageQuestions,
    is_active: true,
    sort_order: 3,
    organization_id: null,
    created_at: daysAgo(90),
    updated_at: daysAgo(90),
  },
  {
    id: 'et-fire',
    name: 'Fire',
    icon: 'Flame',
    color: '#ea580c',
    description: 'Structure fires, vehicle fires, brush fires, explosions.',
    triage_questions: fireTriageQuestions,
    is_active: true,
    sort_order: 4,
    organization_id: null,
    created_at: daysAgo(90),
    updated_at: daysAgo(90),
  },
  {
    id: 'et-flood',
    name: 'Flood / Water Rescue',
    icon: 'Waves',
    color: '#0284c7',
    description: 'Flash floods, rising water, stranded persons, swift-water rescue.',
    triage_questions: floodTriageQuestions,
    is_active: true,
    sort_order: 5,
    organization_id: null,
    created_at: daysAgo(90),
    updated_at: daysAgo(90),
  },
  {
    id: 'et-vehicular',
    name: 'Vehicular Accident',
    icon: 'Car',
    color: '#ca8a04',
    description: 'Road crashes, overturned vehicles, pedestrians struck.',
    triage_questions: medicalTriageQuestions,
    is_active: true,
    sort_order: 6,
    organization_id: null,
    created_at: daysAgo(90),
    updated_at: daysAgo(90),
  },
  {
    id: 'et-missing',
    name: 'Missing Person',
    icon: 'UserSearch',
    color: '#7c3aed',
    description: 'Missing children, elderly wandering, lost hikers.',
    triage_questions: [
      { id: 'miss-q1', question: 'Age of missing person', type: 'number', required: true },
      { id: 'miss-q2', question: 'Last known location', type: 'text', required: true },
      { id: 'miss-q3', question: 'How long have they been missing?', type: 'select', options: ['Less than 1 hour', '1-3 hours', '3-6 hours', 'More than 6 hours'], required: true },
    ],
    is_active: true,
    sort_order: 7,
    organization_id: null,
    created_at: daysAgo(90),
    updated_at: daysAgo(90),
  },
  {
    id: 'et-crime',
    name: 'Crime / Security',
    icon: 'ShieldAlert',
    color: '#be123c',
    description: 'Robbery, assault, domestic violence, suspicious activity.',
    triage_questions: [
      { id: 'crime-q1', question: 'Is the suspect still present?', type: 'boolean', required: true },
      { id: 'crime-q2', question: 'Are there any injuries?', type: 'boolean', required: true },
      { id: 'crime-q3', question: 'Type of incident', type: 'select', options: ['Robbery', 'Assault', 'Domestic violence', 'Trespassing', 'Other'], required: true },
    ],
    is_active: true,
    sort_order: 8,
    organization_id: null,
    created_at: daysAgo(90),
    updated_at: daysAgo(90),
  },
  {
    id: 'et-animal',
    name: 'Animal Rescue',
    icon: 'PawPrint',
    color: '#15803d',
    description: 'Stray animals, animal attacks, wildlife in distress.',
    triage_questions: [
      { id: 'anim-q1', question: 'Type of animal', type: 'text', required: true },
      { id: 'anim-q2', question: 'Is anyone injured?', type: 'boolean', required: true },
    ],
    is_active: true,
    sort_order: 9,
    organization_id: null,
    created_at: daysAgo(90),
    updated_at: daysAgo(90),
  },
  {
    id: 'et-disaster',
    name: 'Natural Disaster',
    icon: 'CloudLightning',
    color: '#92400e',
    description: 'Earthquake, landslide, typhoon damage, structural collapse.',
    triage_questions: [
      { id: 'dis-q1', question: 'Type of disaster', type: 'select', options: ['Earthquake', 'Landslide', 'Typhoon damage', 'Structural collapse', 'Other'], required: true },
      { id: 'dis-q2', question: 'Are people trapped?', type: 'boolean', required: true },
      { id: 'dis-q3', question: 'Estimated number of families affected', type: 'number', required: false },
    ],
    is_active: true,
    sort_order: 10,
    organization_id: null,
    created_at: daysAgo(90),
    updated_at: daysAgo(90),
  },
  {
    id: 'et-other',
    name: 'Other Emergency',
    icon: 'AlertTriangle',
    color: '#6b7280',
    description: 'Any emergency not covered by the above categories.',
    triage_questions: [
      { id: 'oth-q1', question: 'Describe the emergency briefly', type: 'text', required: true },
    ],
    is_active: true,
    sort_order: 11,
    organization_id: null,
    created_at: daysAgo(90),
    updated_at: daysAgo(90),
  },
]

// ============================================================
// REGISTERED RESIDENTS (8)
// ============================================================

export const DEMO_RESIDENTS: ResidentProfile[] = [
  {
    id: 'res-001', user_id: 'uid-res-001', role: 'resident',
    full_name: 'Maria Clara Santos', email: 'mariasantos@email.com', phone: '0917-201-0001',
    avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001',
    is_active: true, last_login_at: hoursAgo(2), created_at: daysAgo(30), updated_at: daysAgo(1),
    date_of_birth: '1985-04-12', address: '12 Sampaguita St.', barangay: 'Poblacion',
    municipality: 'Bayani', province: 'Laguna', id_type: 'national_id',
    id_number: '****-****-3421', id_front_url: null, id_back_url: null,
    emergency_contact_name: 'Jose Santos', emergency_contact_phone: '0917-201-9001',
    emergency_contact_relationship: 'Spouse',
    registration_status: 'approved', verified_at: daysAgo(25), verified_by: 'uid-verif-001',
    rejection_reason: null, more_info_request: null,
  },
  {
    id: 'res-002', user_id: 'uid-res-002', role: 'resident',
    full_name: 'Jose Rizal Mendoza', email: 'josemendoza@email.com', phone: '0918-202-0002',
    avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001',
    is_active: true, last_login_at: hoursAgo(48), created_at: daysAgo(20), updated_at: daysAgo(3),
    date_of_birth: '1992-08-19', address: '45 Aguinaldo Ave.', barangay: 'San Isidro',
    municipality: 'Bayani', province: 'Laguna', id_type: 'drivers_license',
    id_number: '****-****-7892', id_front_url: null, id_back_url: null,
    emergency_contact_name: 'Ana Mendoza', emergency_contact_phone: '0918-202-9002',
    emergency_contact_relationship: 'Mother',
    registration_status: 'approved', verified_at: daysAgo(15), verified_by: 'uid-verif-001',
    rejection_reason: null, more_info_request: null,
  },
  {
    id: 'res-003', user_id: 'uid-res-003', role: 'resident',
    full_name: 'Nena Dela Rosa', email: 'nelarosa@email.com', phone: '0919-203-0003',
    avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001',
    is_active: true, last_login_at: null, created_at: daysAgo(5), updated_at: daysAgo(2),
    date_of_birth: '1970-11-30', address: '8 Rizal Blvd.', barangay: 'Santo Niño',
    municipality: 'Bayani', province: 'Laguna', id_type: 'philhealth',
    id_number: '****-****-1234', id_front_url: null, id_back_url: null,
    emergency_contact_name: 'Pedro Dela Rosa', emergency_contact_phone: '0919-203-9003',
    emergency_contact_relationship: 'Son',
    registration_status: 'under_review', verified_at: null, verified_by: null,
    rejection_reason: null, more_info_request: null,
  },
  {
    id: 'res-004', user_id: 'uid-res-004', role: 'resident',
    full_name: 'Ramon Ilustrado Villanueva', email: 'ramon.villanueva@email.com', phone: '0920-204-0004',
    avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001',
    is_active: true, last_login_at: hoursAgo(72), created_at: daysAgo(10), updated_at: daysAgo(7),
    date_of_birth: '1988-02-14', address: '22 Mabini St.', barangay: 'San Jose',
    municipality: 'Bayani', province: 'Laguna', id_type: 'sss',
    id_number: '****-****-5678', id_front_url: null, id_back_url: null,
    emergency_contact_name: 'Lucia Villanueva', emergency_contact_phone: '0920-204-9004',
    emergency_contact_relationship: 'Sister',
    registration_status: 'more_info_required', verified_at: null, verified_by: null,
    rejection_reason: null, more_info_request: 'Please upload a clearer copy of your ID back page.',
  },
  {
    id: 'res-005', user_id: 'uid-res-005', role: 'resident',
    full_name: 'Cynthia Aquino Reyes', email: 'cynthiareyes@email.com', phone: '0921-205-0005',
    avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001',
    is_active: true, last_login_at: hoursAgo(120), created_at: daysAgo(45), updated_at: daysAgo(40),
    date_of_birth: '1995-06-30', address: '67 Luna Blvd.', barangay: 'Bagong Pag-asa',
    municipality: 'Bayani', province: 'Laguna', id_type: 'passport',
    id_number: '****-****-9012', id_front_url: null, id_back_url: null,
    emergency_contact_name: 'Roberto Reyes', emergency_contact_phone: '0921-205-9005',
    emergency_contact_relationship: 'Father',
    registration_status: 'approved', verified_at: daysAgo(40), verified_by: 'uid-verif-001',
    rejection_reason: null, more_info_request: null,
  },
  {
    id: 'res-006', user_id: 'uid-res-006', role: 'resident',
    full_name: 'Florencio Macaraeg Bautista', email: 'florencio.bautista@email.com', phone: '0922-206-0006',
    avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001',
    is_active: true, last_login_at: null, created_at: daysAgo(3), updated_at: daysAgo(3),
    date_of_birth: '2000-09-01', address: '3 Bonifacio St.', barangay: 'Mabuhay',
    municipality: 'Bayani', province: 'Laguna', id_type: 'voters_id',
    id_number: null, id_front_url: null, id_back_url: null,
    emergency_contact_name: 'Gloria Bautista', emergency_contact_phone: '0922-206-9006',
    emergency_contact_relationship: 'Mother',
    registration_status: 'submitted', verified_at: null, verified_by: null,
    rejection_reason: null, more_info_request: null,
  },
  {
    id: 'res-007', user_id: 'uid-res-007', role: 'resident',
    full_name: 'Ligaya Navarro Cruz', email: 'ligayacruz@email.com', phone: '0923-207-0007',
    avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001',
    is_active: false, last_login_at: daysAgo(60), created_at: daysAgo(75), updated_at: daysAgo(60),
    date_of_birth: '1960-03-22', address: '100 Magsaysay St.', barangay: 'Pag-asa',
    municipality: 'Bayani', province: 'Laguna', id_type: 'senior_citizen_id',
    id_number: '****-****-3456', id_front_url: null, id_back_url: null,
    emergency_contact_name: 'Mario Cruz', emergency_contact_phone: '0923-207-9007',
    emergency_contact_relationship: 'Son',
    registration_status: 'rejected', verified_at: null, verified_by: 'uid-verif-001',
    rejection_reason: 'Submitted ID appears to be expired. Please resubmit with a valid ID.',
    more_info_request: null,
  },
  {
    id: 'res-008', user_id: 'uid-res-008', role: 'resident',
    full_name: 'Benedicto Ramos Fernandez', email: 'bfernandez@email.com', phone: '0924-208-0008',
    avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001',
    is_active: true, last_login_at: minutesAgo(30), created_at: daysAgo(60), updated_at: daysAgo(1),
    date_of_birth: '1978-12-05', address: '55 Del Pilar St.', barangay: 'Maligaya',
    municipality: 'Bayani', province: 'Laguna', id_type: 'national_id',
    id_number: '****-****-7890', id_front_url: null, id_back_url: null,
    emergency_contact_name: 'Liza Fernandez', emergency_contact_phone: '0924-208-9008',
    emergency_contact_relationship: 'Wife',
    registration_status: 'approved', verified_at: daysAgo(55), verified_by: 'uid-verif-001',
    rejection_reason: null, more_info_request: null,
  },
]

// ============================================================
// STAFF PROFILES / RESPONDERS (used in units)
// ============================================================

export const DEMO_RESPONDERS: UserProfile[] = [
  // Alpha unit
  { id: 'rsp-a1', user_id: 'uid-rsp-a1', role: 'team_leader', full_name: 'Sgt. Antonio Dela Torre', email: 'adelatorre@rescue.bayani.gov.ph', phone: '0917-300-0001', avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001', is_active: true, last_login_at: hoursAgo(1), created_at: daysAgo(90), updated_at: daysAgo(1) },
  { id: 'rsp-a2', user_id: 'uid-rsp-a2', role: 'responder', full_name: 'Cpl. Jerome Castillo', email: 'jcastillo@rescue.bayani.gov.ph', phone: '0917-300-0002', avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001', is_active: true, last_login_at: hoursAgo(2), created_at: daysAgo(90), updated_at: daysAgo(1) },
  { id: 'rsp-a3', user_id: 'uid-rsp-a3', role: 'responder', full_name: 'PFC. Rowena Aguilar', email: 'raguilar@rescue.bayani.gov.ph', phone: '0917-300-0003', avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001', is_active: true, last_login_at: hoursAgo(3), created_at: daysAgo(80), updated_at: daysAgo(1) },
  { id: 'rsp-a4', user_id: 'uid-rsp-a4', role: 'responder', full_name: 'PFC. Marlon Buenaventura', email: 'mbuenaventura@rescue.bayani.gov.ph', phone: '0917-300-0004', avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001', is_active: true, last_login_at: hoursAgo(4), created_at: daysAgo(80), updated_at: daysAgo(1) },
  // Bravo unit
  { id: 'rsp-b1', user_id: 'uid-rsp-b1', role: 'team_leader', full_name: 'Sgt. Patricia Soriano', email: 'psoriano@rescue.bayani.gov.ph', phone: '0918-300-0001', avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001', is_active: true, last_login_at: hoursAgo(1), created_at: daysAgo(90), updated_at: daysAgo(1) },
  { id: 'rsp-b2', user_id: 'uid-rsp-b2', role: 'responder', full_name: 'Cpl. Dennis Corpuz', email: 'dcorpuz@rescue.bayani.gov.ph', phone: '0918-300-0002', avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001', is_active: true, last_login_at: hoursAgo(5), created_at: daysAgo(85), updated_at: daysAgo(1) },
  { id: 'rsp-b3', user_id: 'uid-rsp-b3', role: 'responder', full_name: 'PFC. Alma Pascual', email: 'apascual@rescue.bayani.gov.ph', phone: '0918-300-0003', avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001', is_active: true, last_login_at: hoursAgo(6), created_at: daysAgo(75), updated_at: daysAgo(1) },
  // Charlie unit
  { id: 'rsp-c1', user_id: 'uid-rsp-c1', role: 'team_leader', full_name: 'Sgt. Roberto Lim', email: 'rlim@rescue.bayani.gov.ph', phone: '0919-300-0001', avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001', is_active: true, last_login_at: hoursAgo(2), created_at: daysAgo(90), updated_at: daysAgo(1) },
  { id: 'rsp-c2', user_id: 'uid-rsp-c2', role: 'responder', full_name: 'Cpl. Francis Navarro', email: 'fnavarro@rescue.bayani.gov.ph', phone: '0919-300-0002', avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001', is_active: true, last_login_at: hoursAgo(3), created_at: daysAgo(70), updated_at: daysAgo(1) },
  { id: 'rsp-c3', user_id: 'uid-rsp-c3', role: 'responder', full_name: 'PFC. Divina Reyes', email: 'dreyes@rescue.bayani.gov.ph', phone: '0919-300-0003', avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001', is_active: true, last_login_at: hoursAgo(4), created_at: daysAgo(70), updated_at: daysAgo(1) },
  // Delta unit
  { id: 'rsp-d1', user_id: 'uid-rsp-d1', role: 'team_leader', full_name: 'Sgt. Miguel Santos', email: 'msantos@rescue.bayani.gov.ph', phone: '0920-300-0001', avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001', is_active: true, last_login_at: hoursAgo(8), created_at: daysAgo(90), updated_at: daysAgo(2) },
  { id: 'rsp-d2', user_id: 'uid-rsp-d2', role: 'responder', full_name: 'Cpl. Teresita Cruz', email: 'tcruz@rescue.bayani.gov.ph', phone: '0920-300-0002', avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001', is_active: true, last_login_at: hoursAgo(9), created_at: daysAgo(65), updated_at: daysAgo(2) },
  { id: 'rsp-d3', user_id: 'uid-rsp-d3', role: 'responder', full_name: 'PFC. Edwin Gomez', email: 'egomez@rescue.bayani.gov.ph', phone: '0920-300-0003', avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001', is_active: false, last_login_at: daysAgo(3), created_at: daysAgo(60), updated_at: daysAgo(3) },
  { id: 'rsp-d4', user_id: 'uid-rsp-d4', role: 'responder', full_name: 'PFC. Josephine Dela Cruz', email: 'jdelacruz@rescue.bayani.gov.ph', phone: '0920-300-0004', avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001', is_active: true, last_login_at: hoursAgo(10), created_at: daysAgo(55), updated_at: daysAgo(2) },
  // Dispatcher & Verifier
  { id: 'usr-disp', user_id: 'uid-disp', role: 'dispatcher', full_name: 'Danilo Macaraeg', email: 'dispatcher@rescue.bayani.gov.ph', phone: '0917-400-0001', avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001', is_active: true, last_login_at: minutesAgo(15), created_at: daysAgo(90), updated_at: daysAgo(1) },
  { id: 'usr-verif', user_id: 'uid-verif-001', role: 'verifier', full_name: 'Ana Bautista', email: 'verifier@rescue.bayani.gov.ph', phone: '0917-400-0002', avatar_url: null, organization_id: 'org-bayani-001', municipality_id: 'mun-001', is_active: true, last_login_at: minutesAgo(45), created_at: daysAgo(90), updated_at: daysAgo(1) },
]

// ============================================================
// RESCUE UNITS (4)
// ============================================================

export const DEMO_RESCUE_UNITS: RescueUnit[] = [
  {
    id: 'unit-alpha',
    name: 'Rescue Team Alpha',
    code: 'ALPHA-1',
    organization_id: 'org-bayani-001',
    municipality_id: 'mun-001',
    team_leader_id: 'uid-rsp-a1',
    team_leader_name: 'Sgt. Antonio Dela Torre',
    status: 'dispatched',
    contact_number: '0917-300-0001',
    vehicle_info: { plate_number: 'LAG-1001', type: 'ambulance', model: 'Toyota HiAce Ambulance', color: 'White/Red', capacity: 6 },
    equipment: ['AED', 'Oxygen tank', 'Stretcher', 'First aid kit', 'Spine board', 'BVM'],
    specializations: ['Advanced Life Support', 'Trauma Response'],
    telegram_chat_id: '-1001000000001',
    current_lat: 14.1640,
    current_lng: 121.2445,
    last_location_update: minutesAgo(5),
    is_active: true,
    created_at: daysAgo(90),
    updated_at: minutesAgo(5),
    members: [
      { id: 'mbr-a1', unit_id: 'unit-alpha', user_id: 'uid-rsp-a1', user_name: 'Sgt. Antonio Dela Torre', role: 'team_leader', is_active: true, joined_at: daysAgo(90), left_at: null },
      { id: 'mbr-a2', unit_id: 'unit-alpha', user_id: 'uid-rsp-a2', user_name: 'Cpl. Jerome Castillo', role: 'member', is_active: true, joined_at: daysAgo(90), left_at: null },
      { id: 'mbr-a3', unit_id: 'unit-alpha', user_id: 'uid-rsp-a3', user_name: 'PFC. Rowena Aguilar', role: 'member', is_active: true, joined_at: daysAgo(80), left_at: null },
      { id: 'mbr-a4', unit_id: 'unit-alpha', user_id: 'uid-rsp-a4', user_name: 'PFC. Marlon Buenaventura', role: 'member', is_active: true, joined_at: daysAgo(80), left_at: null },
    ],
  },
  {
    id: 'unit-bravo',
    name: 'Rescue Team Bravo',
    code: 'BRAVO-1',
    organization_id: 'org-bayani-001',
    municipality_id: 'mun-001',
    team_leader_id: 'uid-rsp-b1',
    team_leader_name: 'Sgt. Patricia Soriano',
    status: 'on_scene',
    contact_number: '0918-300-0001',
    vehicle_info: { plate_number: 'LAG-1002', type: 'fire_truck', model: 'Isuzu Fire Truck', color: 'Red', capacity: 8 },
    equipment: ['Fire hose', 'Jaws of Life', 'Thermal camera', 'SCBA', 'Ladder', 'Fire extinguisher'],
    specializations: ['Fire Suppression', 'Extrication', 'Hazmat'],
    telegram_chat_id: '-1001000000002',
    current_lat: 14.1615,
    current_lng: 121.2410,
    last_location_update: minutesAgo(10),
    is_active: true,
    created_at: daysAgo(90),
    updated_at: minutesAgo(10),
    members: [
      { id: 'mbr-b1', unit_id: 'unit-bravo', user_id: 'uid-rsp-b1', user_name: 'Sgt. Patricia Soriano', role: 'team_leader', is_active: true, joined_at: daysAgo(90), left_at: null },
      { id: 'mbr-b2', unit_id: 'unit-bravo', user_id: 'uid-rsp-b2', user_name: 'Cpl. Dennis Corpuz', role: 'member', is_active: true, joined_at: daysAgo(85), left_at: null },
      { id: 'mbr-b3', unit_id: 'unit-bravo', user_id: 'uid-rsp-b3', user_name: 'PFC. Alma Pascual', role: 'member', is_active: true, joined_at: daysAgo(75), left_at: null },
    ],
  },
  {
    id: 'unit-charlie',
    name: 'Rescue Team Charlie',
    code: 'CHARLIE-1',
    organization_id: 'org-bayani-001',
    municipality_id: 'mun-001',
    team_leader_id: 'uid-rsp-c1',
    team_leader_name: 'Sgt. Roberto Lim',
    status: 'available',
    contact_number: '0919-300-0001',
    vehicle_info: { plate_number: 'LAG-1003', type: 'rescue_vehicle', model: 'Nissan Patrol 4x4', color: 'Blue/White', capacity: 5 },
    equipment: ['Rope rescue kit', 'Water rescue equipment', 'Inflatable boat', 'Life vests', 'Dive gear'],
    specializations: ['Water Rescue', 'High Angle Rescue', 'Search and Rescue'],
    telegram_chat_id: '-1001000000003',
    current_lat: 14.1650,
    current_lng: 121.2400,
    last_location_update: minutesAgo(20),
    is_active: true,
    created_at: daysAgo(90),
    updated_at: minutesAgo(20),
    members: [
      { id: 'mbr-c1', unit_id: 'unit-charlie', user_id: 'uid-rsp-c1', user_name: 'Sgt. Roberto Lim', role: 'team_leader', is_active: true, joined_at: daysAgo(90), left_at: null },
      { id: 'mbr-c2', unit_id: 'unit-charlie', user_id: 'uid-rsp-c2', user_name: 'Cpl. Francis Navarro', role: 'member', is_active: true, joined_at: daysAgo(70), left_at: null },
      { id: 'mbr-c3', unit_id: 'unit-charlie', user_id: 'uid-rsp-c3', user_name: 'PFC. Divina Reyes', role: 'member', is_active: true, joined_at: daysAgo(70), left_at: null },
    ],
  },
  {
    id: 'unit-delta',
    name: 'Rescue Team Delta',
    code: 'DELTA-1',
    organization_id: 'org-bayani-001',
    municipality_id: 'mun-001',
    team_leader_id: 'uid-rsp-d1',
    team_leader_name: 'Sgt. Miguel Santos',
    status: 'off_duty',
    contact_number: '0920-300-0001',
    vehicle_info: { plate_number: 'LAG-1004', type: 'ambulance', model: 'Toyota Hiace', color: 'White', capacity: 6 },
    equipment: ['First aid kit', 'Stretcher', 'Oxygen tank', 'AED', 'Splints'],
    specializations: ['Basic Life Support', 'Community Response'],
    telegram_chat_id: '-1001000000004',
    current_lat: null,
    current_lng: null,
    last_location_update: null,
    is_active: true,
    created_at: daysAgo(90),
    updated_at: daysAgo(1),
    members: [
      { id: 'mbr-d1', unit_id: 'unit-delta', user_id: 'uid-rsp-d1', user_name: 'Sgt. Miguel Santos', role: 'team_leader', is_active: true, joined_at: daysAgo(90), left_at: null },
      { id: 'mbr-d2', unit_id: 'unit-delta', user_id: 'uid-rsp-d2', user_name: 'Cpl. Teresita Cruz', role: 'member', is_active: true, joined_at: daysAgo(65), left_at: null },
      { id: 'mbr-d3', unit_id: 'unit-delta', user_id: 'uid-rsp-d3', user_name: 'PFC. Edwin Gomez', role: 'member', is_active: false, joined_at: daysAgo(60), left_at: daysAgo(3) },
      { id: 'mbr-d4', unit_id: 'unit-delta', user_id: 'uid-rsp-d4', user_name: 'PFC. Josephine Dela Cruz', role: 'member', is_active: true, joined_at: daysAgo(55), left_at: null },
    ],
  },
]

// ============================================================
// HELPER: build a timeline entry
// ============================================================

function tl(
  incidentId: string,
  seq: number,
  status: DemoTimelineEntry['status'],
  label: string,
  note: string | null,
  actorName: string,
  actorRole: DemoTimelineEntry['actor_role'],
  createdAt: string
): DemoTimelineEntry {
  return { id: `tl-${incidentId}-${seq}`, incident_id: incidentId, status, label, note, actor_name: actorName, actor_role: actorRole, created_at: createdAt }
}

// ============================================================
// INCIDENTS (12)
// ============================================================

export const DEMO_INCIDENTS: DemoIncident[] = [
  // 1. Critical — cardiac arrest, currently on_the_way
  {
    id: 'inc-001', reference_number: 'INC-2024-001001',
    organization_id: 'org-bayani-001', reporter_id: 'uid-res-001',
    reporter_name: 'Maria Clara Santos', reporter_phone: '0917-201-0001',
    emergency_type_id: 'et-medical',
    emergency_type: { id: 'et-medical', name: 'Medical Emergency', icon: 'Stethoscope', color: '#dc2626' },
    severity: 'critical', status: 'on_the_way',
    description: 'My father collapsed in the kitchen and is unresponsive. He has a history of heart problems.',
    affected_count: 1, has_unconscious: true, has_fire: false, has_flooding: false, has_violence: false,
    latitude: 14.1630, longitude: 121.2422, gps_accuracy: 8,
    address: '12 Sampaguita St.', barangay: 'Poblacion', municipality: 'Bayani',
    assigned_unit_id: 'unit-alpha', assigned_unit_name: 'Rescue Team Alpha',
    is_anonymous: false, is_drill: false,
    created_at: minutesAgo(25), updated_at: minutesAgo(8),
    verified_at: minutesAgo(22), dispatched_at: minutesAgo(18),
    arrived_at: null, resolved_at: null, closed_at: null, resolution_notes: null,
    timeline: [
      tl('inc-001', 1, 'submitted', 'Report Submitted', 'Call received via app.', 'Maria Clara Santos', 'resident', minutesAgo(25)),
      tl('inc-001', 2, 'received', 'Received by Dispatcher', null, 'Danilo Macaraeg', 'dispatcher', minutesAgo(24)),
      tl('inc-001', 3, 'verified', 'Incident Verified', 'Confirmed cardiac arrest via call-back.', 'Ana Bautista', 'verifier', minutesAgo(22)),
      tl('inc-001', 4, 'assigned', 'Unit Assigned', 'Alpha-1 assigned by dispatcher.', 'Danilo Macaraeg', 'dispatcher', minutesAgo(20)),
      tl('inc-001', 5, 'accepted', 'Assignment Accepted', null, 'Sgt. Antonio Dela Torre', 'team_leader', minutesAgo(19)),
      tl('inc-001', 6, 'dispatched', 'Unit Dispatched', 'Team en route.', 'Sgt. Antonio Dela Torre', 'team_leader', minutesAgo(18)),
      tl('inc-001', 7, 'on_the_way', 'On the Way', 'ETA 7 minutes.', 'Sgt. Antonio Dela Torre', 'team_leader', minutesAgo(8)),
    ],
  },
  // 2. High — structure fire, currently arrived
  {
    id: 'inc-002', reference_number: 'INC-2024-001002',
    organization_id: 'org-bayani-001', reporter_id: null,
    reporter_name: 'Anonymous', reporter_phone: '0918-555-0002',
    emergency_type_id: 'et-fire',
    emergency_type: { id: 'et-fire', name: 'Fire', icon: 'Flame', color: '#ea580c' },
    severity: 'high', status: 'operation_in_progress',
    description: 'Sari-sari store on fire, smoke spreading to adjacent house. No one trapped.',
    affected_count: 3, has_unconscious: false, has_fire: true, has_flooding: false, has_violence: false,
    latitude: 14.1615, longitude: 121.2410, gps_accuracy: 15,
    address: '25 Mabini St.', barangay: 'San Isidro', municipality: 'Bayani',
    assigned_unit_id: 'unit-bravo', assigned_unit_name: 'Rescue Team Bravo',
    is_anonymous: true, is_drill: false,
    created_at: hoursAgo(1), updated_at: minutesAgo(15),
    verified_at: hoursAgo(1), dispatched_at: minutesAgo(55),
    arrived_at: minutesAgo(45), resolved_at: null, closed_at: null, resolution_notes: null,
    timeline: [
      tl('inc-002', 1, 'submitted', 'Report Submitted', null, 'Anonymous', 'resident', hoursAgo(1)),
      tl('inc-002', 2, 'received', 'Received by Dispatcher', null, 'Danilo Macaraeg', 'dispatcher', minutesAgo(59)),
      tl('inc-002', 3, 'verified', 'Incident Verified', 'Confirmed fire via CCTV camera.', 'Danilo Macaraeg', 'dispatcher', minutesAgo(57)),
      tl('inc-002', 4, 'assigned', 'Unit Assigned', null, 'Danilo Macaraeg', 'dispatcher', minutesAgo(56)),
      tl('inc-002', 5, 'accepted', 'Assignment Accepted', null, 'Sgt. Patricia Soriano', 'team_leader', minutesAgo(55)),
      tl('inc-002', 6, 'dispatched', 'Unit Dispatched', null, 'Sgt. Patricia Soriano', 'team_leader', minutesAgo(55)),
      tl('inc-002', 7, 'on_the_way', 'On the Way', null, 'Sgt. Patricia Soriano', 'team_leader', minutesAgo(50)),
      tl('inc-002', 8, 'arrived', 'Arrived on Scene', 'Two fire hoses deployed.', 'Sgt. Patricia Soriano', 'team_leader', minutesAgo(45)),
      tl('inc-002', 9, 'operation_in_progress', 'Operation in Progress', 'Fire partially contained.', 'Sgt. Patricia Soriano', 'team_leader', minutesAgo(15)),
    ],
  },
  // 3. Critical — vehicular accident with injuries, dispatched
  {
    id: 'inc-003', reference_number: 'INC-2024-001003',
    organization_id: 'org-bayani-001', reporter_id: 'uid-res-002',
    reporter_name: 'Jose Rizal Mendoza', reporter_phone: '0918-202-0002',
    emergency_type_id: 'et-vehicular',
    emergency_type: { id: 'et-vehicular', name: 'Vehicular Accident', icon: 'Car', color: '#ca8a04' },
    severity: 'critical', status: 'arrived',
    description: 'Head-on collision between a motorcycle and a tricycle. Two persons injured, one unconscious.',
    affected_count: 2, has_unconscious: true, has_fire: false, has_flooding: false, has_violence: false,
    latitude: 14.1645, longitude: 121.2460, gps_accuracy: 10,
    address: 'National Highway near Km. 42', barangay: 'Santo Niño', municipality: 'Bayani',
    assigned_unit_id: 'unit-alpha', assigned_unit_name: 'Rescue Team Alpha',
    is_anonymous: false, is_drill: false,
    created_at: hoursAgo(2), updated_at: minutesAgo(30),
    verified_at: hoursAgo(2), dispatched_at: hoursAgo(2),
    arrived_at: minutesAgo(30), resolved_at: null, closed_at: null, resolution_notes: null,
    timeline: [
      tl('inc-003', 1, 'submitted', 'Report Submitted', null, 'Jose Rizal Mendoza', 'resident', hoursAgo(2)),
      tl('inc-003', 2, 'received', 'Received by Dispatcher', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(2)),
      tl('inc-003', 3, 'verified', 'Incident Verified', null, 'Ana Bautista', 'verifier', hoursAgo(2)),
      tl('inc-003', 4, 'assigned', 'Unit Assigned', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(2)),
      tl('inc-003', 5, 'dispatched', 'Unit Dispatched', null, 'Sgt. Antonio Dela Torre', 'team_leader', hoursAgo(2)),
      tl('inc-003', 6, 'on_the_way', 'On the Way', null, 'Sgt. Antonio Dela Torre', 'team_leader', minutesAgo(50)),
      tl('inc-003', 7, 'arrived', 'Arrived on Scene', 'Victim extricated. Preparing for transport.', 'Sgt. Antonio Dela Torre', 'team_leader', minutesAgo(30)),
    ],
  },
  // 4. Medium — flood, verification_pending
  {
    id: 'inc-004', reference_number: 'INC-2024-001004',
    organization_id: 'org-bayani-001', reporter_id: 'uid-res-005',
    reporter_name: 'Cynthia Aquino Reyes', reporter_phone: '0921-205-0005',
    emergency_type_id: 'et-flood',
    emergency_type: { id: 'et-flood', name: 'Flood / Water Rescue', icon: 'Waves', color: '#0284c7' },
    severity: 'medium', status: 'verification_pending',
    description: 'Floodwater rising fast near the river bank. Several houses are knee-deep in water.',
    affected_count: 12, has_unconscious: false, has_fire: false, has_flooding: true, has_violence: false,
    latitude: 14.1598, longitude: 121.2395, gps_accuracy: 20,
    address: 'Near Bayani River, Barangay Pag-asa', barangay: 'Pag-asa', municipality: 'Bayani',
    assigned_unit_id: null, assigned_unit_name: null,
    is_anonymous: false, is_drill: false,
    created_at: minutesAgo(10), updated_at: minutesAgo(8),
    verified_at: null, dispatched_at: null,
    arrived_at: null, resolved_at: null, closed_at: null, resolution_notes: null,
    timeline: [
      tl('inc-004', 1, 'submitted', 'Report Submitted', null, 'Cynthia Aquino Reyes', 'resident', minutesAgo(10)),
      tl('inc-004', 2, 'received', 'Received by Dispatcher', null, 'Danilo Macaraeg', 'dispatcher', minutesAgo(8)),
      tl('inc-004', 3, 'verification_pending', 'Verification Pending', 'Attempting to call back reporter.', 'Ana Bautista', 'verifier', minutesAgo(8)),
    ],
  },
  // 5. Low — missing elderly, submitted just now
  {
    id: 'inc-005', reference_number: 'INC-2024-001005',
    organization_id: 'org-bayani-001', reporter_id: null,
    reporter_name: 'Ricardo Castillo', reporter_phone: '0922-555-0005',
    emergency_type_id: 'et-missing',
    emergency_type: { id: 'et-missing', name: 'Missing Person', icon: 'UserSearch', color: '#7c3aed' },
    severity: 'medium', status: 'submitted',
    description: '78-year-old grandmother with dementia has been missing for 3 hours. Last seen near the market.',
    affected_count: 1, has_unconscious: false, has_fire: false, has_flooding: false, has_violence: false,
    latitude: 14.1655, longitude: 121.2420, gps_accuracy: 30,
    address: 'Public Market, Poblacion', barangay: 'Poblacion', municipality: 'Bayani',
    assigned_unit_id: null, assigned_unit_name: null,
    is_anonymous: false, is_drill: false,
    created_at: minutesAgo(3), updated_at: minutesAgo(3),
    verified_at: null, dispatched_at: null,
    arrived_at: null, resolved_at: null, closed_at: null, resolution_notes: null,
    timeline: [
      tl('inc-005', 1, 'submitted', 'Report Submitted', null, 'Ricardo Castillo', 'resident', minutesAgo(3)),
    ],
  },
  // 6. Resolved — medical (yesterday)
  {
    id: 'inc-006', reference_number: 'INC-2024-001006',
    organization_id: 'org-bayani-001', reporter_id: 'uid-res-008',
    reporter_name: 'Benedicto Ramos Fernandez', reporter_phone: '0924-208-0008',
    emergency_type_id: 'et-medical',
    emergency_type: { id: 'et-medical', name: 'Medical Emergency', icon: 'Stethoscope', color: '#dc2626' },
    severity: 'high', status: 'resolved',
    description: 'Severe asthma attack, patient unable to breathe. Adult male, 45 years old.',
    affected_count: 1, has_unconscious: false, has_fire: false, has_flooding: false, has_violence: false,
    latitude: 14.1618, longitude: 121.2435, gps_accuracy: 5,
    address: '55 Del Pilar St.', barangay: 'Maligaya', municipality: 'Bayani',
    assigned_unit_id: 'unit-alpha', assigned_unit_name: 'Rescue Team Alpha',
    is_anonymous: false, is_drill: false,
    created_at: hoursAgo(18), updated_at: hoursAgo(16),
    verified_at: hoursAgo(18), dispatched_at: hoursAgo(18),
    arrived_at: hoursAgo(17), resolved_at: hoursAgo(16), closed_at: null, resolution_notes: 'Patient stabilized and transported to Bayani District Hospital.',
    timeline: [
      tl('inc-006', 1, 'submitted', 'Report Submitted', null, 'Benedicto Ramos Fernandez', 'resident', hoursAgo(18)),
      tl('inc-006', 2, 'received', 'Received by Dispatcher', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(18)),
      tl('inc-006', 3, 'verified', 'Verified', null, 'Ana Bautista', 'verifier', hoursAgo(18)),
      tl('inc-006', 4, 'assigned', 'Unit Assigned', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(18)),
      tl('inc-006', 5, 'dispatched', 'Unit Dispatched', null, 'Sgt. Antonio Dela Torre', 'team_leader', hoursAgo(18)),
      tl('inc-006', 6, 'on_the_way', 'On the Way', null, 'Sgt. Antonio Dela Torre', 'team_leader', hoursAgo(17.5)),
      tl('inc-006', 7, 'arrived', 'Arrived', null, 'Sgt. Antonio Dela Torre', 'team_leader', hoursAgo(17)),
      tl('inc-006', 8, 'transporting', 'Transporting to Hospital', 'Patient stable, on O2.', 'Sgt. Antonio Dela Torre', 'team_leader', hoursAgo(16.5)),
      tl('inc-006', 9, 'resolved', 'Resolved', 'Patient admitted to hospital.', 'Danilo Macaraeg', 'dispatcher', hoursAgo(16)),
    ],
  },
  // 7. Closed — vehicular (2 days ago)
  {
    id: 'inc-007', reference_number: 'INC-2024-001007',
    organization_id: 'org-bayani-001', reporter_id: null,
    reporter_name: 'Anonymous', reporter_phone: null,
    emergency_type_id: 'et-vehicular',
    emergency_type: { id: 'et-vehicular', name: 'Vehicular Accident', icon: 'Car', color: '#ca8a04' },
    severity: 'medium', status: 'closed',
    description: 'Minor fender-bender near the school. No injuries reported.',
    affected_count: 0, has_unconscious: false, has_fire: false, has_flooding: false, has_violence: false,
    latitude: 14.1660, longitude: 121.2415, gps_accuracy: null,
    address: 'Bayani Elementary School, Barangay San Jose', barangay: 'San Jose', municipality: 'Bayani',
    assigned_unit_id: 'unit-delta', assigned_unit_name: 'Rescue Team Delta',
    is_anonymous: true, is_drill: false,
    created_at: hoursAgo(36), updated_at: hoursAgo(34),
    verified_at: hoursAgo(36), dispatched_at: hoursAgo(36),
    arrived_at: hoursAgo(35), resolved_at: hoursAgo(34), closed_at: hoursAgo(33),
    resolution_notes: 'No injuries. Assisted drivers with moving vehicles off the road.',
    timeline: [
      tl('inc-007', 1, 'submitted', 'Report Submitted', null, 'Anonymous', 'resident', hoursAgo(36)),
      tl('inc-007', 2, 'received', 'Received', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(36)),
      tl('inc-007', 3, 'verified', 'Verified', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(36)),
      tl('inc-007', 4, 'assigned', 'Assigned', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(36)),
      tl('inc-007', 5, 'dispatched', 'Dispatched', null, 'Sgt. Miguel Santos', 'team_leader', hoursAgo(36)),
      tl('inc-007', 6, 'arrived', 'Arrived', null, 'Sgt. Miguel Santos', 'team_leader', hoursAgo(35)),
      tl('inc-007', 7, 'resolved', 'Resolved', null, 'Sgt. Miguel Santos', 'team_leader', hoursAgo(34)),
      tl('inc-007', 8, 'closed', 'Closed', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(33)),
    ],
  },
  // 8. False alert
  {
    id: 'inc-008', reference_number: 'INC-2024-001008',
    organization_id: 'org-bayani-001', reporter_id: null,
    reporter_name: 'Anonymous', reporter_phone: '0999-555-0008',
    emergency_type_id: 'et-fire',
    emergency_type: { id: 'et-fire', name: 'Fire', icon: 'Flame', color: '#ea580c' },
    severity: 'high', status: 'false_alert',
    description: 'Smoke coming from abandoned warehouse.',
    affected_count: 0, has_unconscious: false, has_fire: true, has_flooding: false, has_violence: false,
    latitude: 14.1625, longitude: 121.2450, gps_accuracy: null,
    address: 'Purok 4, Bagong Silang', barangay: 'Bagong Silang', municipality: 'Bayani',
    assigned_unit_id: 'unit-bravo', assigned_unit_name: 'Rescue Team Bravo',
    is_anonymous: true, is_drill: false,
    created_at: hoursAgo(48), updated_at: hoursAgo(46),
    verified_at: hoursAgo(48), dispatched_at: hoursAgo(48),
    arrived_at: hoursAgo(47), resolved_at: null, closed_at: null,
    resolution_notes: 'Upon inspection: smoke was from burning garbage, not a structure fire.',
    timeline: [
      tl('inc-008', 1, 'submitted', 'Report Submitted', null, 'Anonymous', 'resident', hoursAgo(48)),
      tl('inc-008', 2, 'received', 'Received', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(48)),
      tl('inc-008', 3, 'assigned', 'Unit Assigned', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(48)),
      tl('inc-008', 4, 'arrived', 'Arrived', null, 'Sgt. Patricia Soriano', 'team_leader', hoursAgo(47)),
      tl('inc-008', 5, 'false_alert', 'Marked False Alert', 'Garbage burning, not a structure fire.', 'Sgt. Patricia Soriano', 'team_leader', hoursAgo(46)),
    ],
  },
  // 9. Resolved — animal rescue
  {
    id: 'inc-009', reference_number: 'INC-2024-001009',
    organization_id: 'org-bayani-001', reporter_id: 'uid-res-001',
    reporter_name: 'Maria Clara Santos', reporter_phone: '0917-201-0001',
    emergency_type_id: 'et-animal',
    emergency_type: { id: 'et-animal', name: 'Animal Rescue', icon: 'PawPrint', color: '#15803d' },
    severity: 'low', status: 'closed',
    description: 'Dog trapped under collapsed fence after last night\'s storm. Still alive.',
    affected_count: 0, has_unconscious: false, has_fire: false, has_flooding: false, has_violence: false,
    latitude: 14.1637, longitude: 121.2428, gps_accuracy: 12,
    address: '14 Sampaguita St.', barangay: 'Poblacion', municipality: 'Bayani',
    assigned_unit_id: 'unit-charlie', assigned_unit_name: 'Rescue Team Charlie',
    is_anonymous: false, is_drill: false,
    created_at: hoursAgo(24), updated_at: hoursAgo(22),
    verified_at: hoursAgo(24), dispatched_at: hoursAgo(23.5),
    arrived_at: hoursAgo(23), resolved_at: hoursAgo(22), closed_at: hoursAgo(22),
    resolution_notes: 'Dog safely rescued and handed to owner.',
    timeline: [
      tl('inc-009', 1, 'submitted', 'Report Submitted', null, 'Maria Clara Santos', 'resident', hoursAgo(24)),
      tl('inc-009', 2, 'received', 'Received', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(24)),
      tl('inc-009', 3, 'assigned', 'Unit Assigned', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(23.5)),
      tl('inc-009', 4, 'arrived', 'Arrived', null, 'Sgt. Roberto Lim', 'team_leader', hoursAgo(23)),
      tl('inc-009', 5, 'resolved', 'Resolved', 'Animal rescued successfully.', 'Sgt. Roberto Lim', 'team_leader', hoursAgo(22)),
      tl('inc-009', 6, 'closed', 'Closed', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(22)),
    ],
  },
  // 10. High — domestic violence, assigned
  {
    id: 'inc-010', reference_number: 'INC-2024-001010',
    organization_id: 'org-bayani-001', reporter_id: null,
    reporter_name: 'Neighbor (Anonymous)', reporter_phone: '0912-555-0010',
    emergency_type_id: 'et-crime',
    emergency_type: { id: 'et-crime', name: 'Crime / Security', icon: 'ShieldAlert', color: '#be123c' },
    severity: 'high', status: 'assigned',
    description: 'Loud argument and sounds of physical altercation from next-door neighbor. Woman screaming for help.',
    affected_count: 2, has_unconscious: false, has_fire: false, has_flooding: false, has_violence: true,
    latitude: 14.1642, longitude: 121.2418, gps_accuracy: 25,
    address: 'Purok 3, Mabuhay', barangay: 'Mabuhay', municipality: 'Bayani',
    assigned_unit_id: 'unit-charlie', assigned_unit_name: 'Rescue Team Charlie',
    is_anonymous: true, is_drill: false,
    created_at: minutesAgo(40), updated_at: minutesAgo(35),
    verified_at: minutesAgo(38), dispatched_at: null,
    arrived_at: null, resolved_at: null, closed_at: null, resolution_notes: null,
    timeline: [
      tl('inc-010', 1, 'submitted', 'Report Submitted', null, 'Neighbor (Anonymous)', 'resident', minutesAgo(40)),
      tl('inc-010', 2, 'received', 'Received', null, 'Danilo Macaraeg', 'dispatcher', minutesAgo(39)),
      tl('inc-010', 3, 'verified', 'Verified', 'Confirmed via call with reporter.', 'Ana Bautista', 'verifier', minutesAgo(38)),
      tl('inc-010', 4, 'assigned', 'Unit Assigned', 'Charlie-1 assigned. PNP also notified.', 'Danilo Macaraeg', 'dispatcher', minutesAgo(35)),
    ],
  },
  // 11. Critical — structural collapse
  {
    id: 'inc-011', reference_number: 'INC-2024-001011',
    organization_id: 'org-bayani-001', reporter_id: 'uid-res-004',
    reporter_name: 'Ramon Ilustrado Villanueva', reporter_phone: '0920-204-0004',
    emergency_type_id: 'et-disaster',
    emergency_type: { id: 'et-disaster', name: 'Natural Disaster', icon: 'CloudLightning', color: '#92400e' },
    severity: 'critical', status: 'resolved',
    description: 'Old building wall collapsed on the street. Three people partially buried. One unconscious.',
    affected_count: 3, has_unconscious: true, has_fire: false, has_flooding: false, has_violence: false,
    latitude: 14.1610, longitude: 121.2440, gps_accuracy: 6,
    address: '22 Mabini St.', barangay: 'San Jose', municipality: 'Bayani',
    assigned_unit_id: 'unit-bravo', assigned_unit_name: 'Rescue Team Bravo',
    is_anonymous: false, is_drill: false,
    created_at: hoursAgo(30), updated_at: hoursAgo(27),
    verified_at: hoursAgo(30), dispatched_at: hoursAgo(30),
    arrived_at: hoursAgo(29), resolved_at: hoursAgo(27), closed_at: null,
    resolution_notes: 'All three victims extracted. Two transferred to Bayani District Hospital. One refused transport.',
    timeline: [
      tl('inc-011', 1, 'submitted', 'Report Submitted', null, 'Ramon Ilustrado Villanueva', 'resident', hoursAgo(30)),
      tl('inc-011', 2, 'received', 'Received', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(30)),
      tl('inc-011', 3, 'verified', 'Verified', null, 'Ana Bautista', 'verifier', hoursAgo(30)),
      tl('inc-011', 4, 'assigned', 'Unit Assigned', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(30)),
      tl('inc-011', 5, 'dispatched', 'Dispatched', null, 'Sgt. Patricia Soriano', 'team_leader', hoursAgo(30)),
      tl('inc-011', 6, 'arrived', 'Arrived', null, 'Sgt. Patricia Soriano', 'team_leader', hoursAgo(29)),
      tl('inc-011', 7, 'operation_in_progress', 'Extraction in Progress', 'Using hydraulic tools.', 'Sgt. Patricia Soriano', 'team_leader', hoursAgo(28.5)),
      tl('inc-011', 8, 'transporting', 'Transporting', 'Two patients en route to hospital.', 'Sgt. Patricia Soriano', 'team_leader', hoursAgo(27.5)),
      tl('inc-011', 9, 'resolved', 'Resolved', 'All victims accounted for.', 'Danilo Macaraeg', 'dispatcher', hoursAgo(27)),
    ],
  },
  // 12. Low — unable to contact
  {
    id: 'inc-012', reference_number: 'INC-2024-001012',
    organization_id: 'org-bayani-001', reporter_id: null,
    reporter_name: 'Unknown', reporter_phone: '0912-555-0012',
    emergency_type_id: 'et-other',
    emergency_type: { id: 'et-other', name: 'Other Emergency', icon: 'AlertTriangle', color: '#6b7280' },
    severity: 'info', status: 'unable_to_contact',
    description: 'Caller reported a suspicious package near the municipal hall then hung up.',
    affected_count: 0, has_unconscious: false, has_fire: false, has_flooding: false, has_violence: false,
    latitude: 14.1634, longitude: 121.2430, gps_accuracy: null,
    address: 'Municipal Hall, Poblacion', barangay: 'Poblacion', municipality: 'Bayani',
    assigned_unit_id: null, assigned_unit_name: null,
    is_anonymous: true, is_drill: false,
    created_at: hoursAgo(6), updated_at: hoursAgo(5),
    verified_at: null, dispatched_at: null,
    arrived_at: null, resolved_at: null, closed_at: null,
    resolution_notes: 'Three call-back attempts made, no answer. Area visually checked — no suspicious package found.',
    timeline: [
      tl('inc-012', 1, 'submitted', 'Report Submitted', null, 'Unknown', 'resident', hoursAgo(6)),
      tl('inc-012', 2, 'received', 'Received', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(6)),
      tl('inc-012', 3, 'verification_pending', 'Verification Pending', 'Attempting to call back.', 'Ana Bautista', 'verifier', hoursAgo(5.8)),
      tl('inc-012', 4, 'unable_to_contact', 'Unable to Contact', 'Three attempts made. No answer.', 'Ana Bautista', 'verifier', hoursAgo(5)),
    ],
  },
  // 13. High — Earthquake, structural damage reported
  {
    id: 'inc-013', reference_number: 'INC-2024-001013',
    organization_id: 'org-bayani-001', reporter_id: 'uid-res-003',
    reporter_name: 'Roberto Garcia', reporter_phone: '0917-201-0003',
    emergency_type_id: 'et-earthquake',
    emergency_type: { id: 'et-earthquake', name: 'Earthquake', icon: 'Activity', color: '#b45309' },
    severity: 'high', status: 'arrived',
    description: 'Strong shaking felt for approximately 15 seconds. Wall cracks in our house and the neighbor\'s roof partially collapsed. Two elderly persons need assistance.',
    affected_count: 8, has_unconscious: false, has_fire: false, has_flooding: false, has_violence: false,
    latitude: 14.1620, longitude: 121.2415, gps_accuracy: 10,
    address: '78 Rizal Ave.', barangay: 'Santo Niño', municipality: 'Bayani',
    assigned_unit_id: 'unit-alpha', assigned_unit_name: 'Rescue Team Alpha',
    is_anonymous: false, is_drill: false,
    created_at: hoursAgo(3), updated_at: minutesAgo(140),
    verified_at: hoursAgo(2.9), dispatched_at: hoursAgo(2.8),
    arrived_at: minutesAgo(140), resolved_at: null, closed_at: null, resolution_notes: null,
    timeline: [
      tl('inc-013', 1, 'submitted', 'Report Submitted', 'Earthquake damage reported via app.', 'Roberto Garcia', 'resident', hoursAgo(3)),
      tl('inc-013', 2, 'received', 'Received by Dispatcher', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(2.95)),
      tl('inc-013', 3, 'verified', 'Incident Verified', 'Multiple reports from same barangay confirm shaking.', 'Ana Bautista', 'verifier', hoursAgo(2.9)),
      tl('inc-013', 4, 'assigned', 'Unit Assigned', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(2.85)),
      tl('inc-013', 5, 'dispatched', 'Unit Dispatched', null, 'Sgt. Antonio Dela Torre', 'team_leader', hoursAgo(2.8)),
      tl('inc-013', 6, 'on_the_way', 'On the Way', 'ETA 10 minutes.', 'Sgt. Antonio Dela Torre', 'team_leader', hoursAgo(2.7)),
      tl('inc-013', 7, 'arrived', 'Arrived on Scene', 'Assessing structural damage.', 'Sgt. Antonio Dela Torre', 'team_leader', minutesAgo(140)),
    ],
  },
  // 14. Critical — Typhoon / Storm, multiple families stranded
  {
    id: 'inc-014', reference_number: 'INC-2024-001014',
    organization_id: 'org-bayani-001', reporter_id: 'uid-res-005',
    reporter_name: 'Elena Mendoza', reporter_phone: '0917-201-0005',
    emergency_type_id: 'et-typhoon',
    emergency_type: { id: 'et-typhoon', name: 'Typhoon / Storm', icon: 'CloudHail', color: '#0369a1' },
    severity: 'critical', status: 'operation_in_progress',
    description: 'Typhoon Odette caused severe flooding and roof damage in Brgy. Bagong Pag-asa. Multiple families stranded on second floors. Power lines down along the national highway.',
    affected_count: 45, has_unconscious: false, has_fire: false, has_flooding: true, has_violence: false,
    latitude: 14.1645, longitude: 121.2450, gps_accuracy: 20,
    address: 'National Highway, Brgy. Bagong Pag-asa', barangay: 'Bagong Pag-asa', municipality: 'Bayani',
    assigned_unit_id: 'unit-charlie', assigned_unit_name: 'Rescue Team Charlie',
    is_anonymous: false, is_drill: false,
    created_at: hoursAgo(8), updated_at: hoursAgo(2),
    verified_at: hoursAgo(7.8), dispatched_at: hoursAgo(7.5),
    arrived_at: hoursAgo(6), resolved_at: null, closed_at: null, resolution_notes: null,
    timeline: [
      tl('inc-014', 1, 'submitted', 'Report Submitted', 'Typhoon damage and flooding reported.', 'Elena Mendoza', 'resident', hoursAgo(8)),
      tl('inc-014', 2, 'received', 'Received by Dispatcher', 'Multiple storm reports incoming.', 'Danilo Macaraeg', 'dispatcher', hoursAgo(7.9)),
      tl('inc-014', 3, 'verified', 'Incident Verified', 'Barangay captain confirmed severe damage.', 'Ana Bautista', 'verifier', hoursAgo(7.8)),
      tl('inc-014', 4, 'assigned', 'Unit Assigned', 'Charlie team deployed with rubber boat.', 'Danilo Macaraeg', 'dispatcher', hoursAgo(7.5)),
      tl('inc-014', 5, 'dispatched', 'Unit Dispatched', null, 'Sgt. Ricardo Marquez', 'team_leader', hoursAgo(7.5)),
      tl('inc-014', 6, 'on_the_way', 'On the Way', 'Roads partially blocked by fallen trees.', 'Sgt. Ricardo Marquez', 'team_leader', hoursAgo(7)),
      tl('inc-014', 7, 'arrived', 'Arrived on Scene', '12 families identified for evacuation.', 'Sgt. Ricardo Marquez', 'team_leader', hoursAgo(6)),
      tl('inc-014', 8, 'operation_in_progress', 'Operation in Progress', '8 families evacuated so far. Continuing rescue operations.', 'Sgt. Ricardo Marquez', 'team_leader', hoursAgo(2)),
    ],
  },
  // 15. Medium — Typhoon aftermath, fallen tree blocking road
  {
    id: 'inc-015', reference_number: 'INC-2024-001015',
    organization_id: 'org-bayani-001', reporter_id: 'uid-res-002',
    reporter_name: 'Juan Paolo Reyes', reporter_phone: '0917-201-0002',
    emergency_type_id: 'et-typhoon',
    emergency_type: { id: 'et-typhoon', name: 'Typhoon / Storm', icon: 'CloudHail', color: '#0369a1' },
    severity: 'medium', status: 'resolved',
    description: 'Large acacia tree fell across the road near San Jose chapel. No injuries but road is completely blocked.',
    affected_count: 0, has_unconscious: false, has_fire: false, has_flooding: false, has_violence: false,
    latitude: 14.1655, longitude: 121.2440, gps_accuracy: 12,
    address: 'Chapel Road, San Jose', barangay: 'San Jose', municipality: 'Bayani',
    assigned_unit_id: 'unit-delta', assigned_unit_name: 'Rescue Team Delta',
    is_anonymous: false, is_drill: false,
    created_at: hoursAgo(10), updated_at: hoursAgo(7),
    verified_at: hoursAgo(9.8), dispatched_at: hoursAgo(9.5),
    arrived_at: hoursAgo(9), resolved_at: hoursAgo(7), closed_at: hoursAgo(7),
    resolution_notes: 'Tree removed with chainsaw. Road cleared and reopened.',
    timeline: [
      tl('inc-015', 1, 'submitted', 'Report Submitted', null, 'Juan Paolo Reyes', 'resident', hoursAgo(10)),
      tl('inc-015', 2, 'received', 'Received', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(9.9)),
      tl('inc-015', 3, 'verified', 'Verified', 'Photo confirms large tree blocking road.', 'Ana Bautista', 'verifier', hoursAgo(9.8)),
      tl('inc-015', 4, 'assigned', 'Unit Assigned', null, 'Danilo Macaraeg', 'dispatcher', hoursAgo(9.5)),
      tl('inc-015', 5, 'dispatched', 'Dispatched', null, 'Sgt. Marco Villanueva', 'team_leader', hoursAgo(9.5)),
      tl('inc-015', 6, 'arrived', 'Arrived', null, 'Sgt. Marco Villanueva', 'team_leader', hoursAgo(9)),
      tl('inc-015', 7, 'operation_in_progress', 'Clearing Road', 'Chainsaw deployed.', 'Sgt. Marco Villanueva', 'team_leader', hoursAgo(8)),
      tl('inc-015', 8, 'resolved', 'Resolved', 'Tree removed. Road reopened.', 'Sgt. Marco Villanueva', 'team_leader', hoursAgo(7)),
    ],
  },
]

// ============================================================
// AUDIT LOG ENTRIES
// ============================================================

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  { id: 'audit-001', actor_id: 'uid-disp', actor_name: 'Danilo Macaraeg', actor_role: 'dispatcher', action: 'create', entity_type: 'incident', entity_id: 'inc-001', previous_values: null, new_values: { status: 'received' }, ip_address: '192.168.1.10', user_agent: 'Mozilla/5.0', organization_id: 'org-bayani-001', created_at: minutesAgo(24) },
  { id: 'audit-002', actor_id: 'uid-verif-001', actor_name: 'Ana Bautista', actor_role: 'verifier', action: 'update', entity_type: 'incident', entity_id: 'inc-001', previous_values: { status: 'received' }, new_values: { status: 'verified' }, ip_address: '192.168.1.11', user_agent: 'Mozilla/5.0', organization_id: 'org-bayani-001', created_at: minutesAgo(22) },
  { id: 'audit-003', actor_id: 'uid-disp', actor_name: 'Danilo Macaraeg', actor_role: 'dispatcher', action: 'update', entity_type: 'incident', entity_id: 'inc-001', previous_values: { status: 'verified' }, new_values: { status: 'assigned', assigned_unit_id: 'unit-alpha' }, ip_address: '192.168.1.10', user_agent: 'Mozilla/5.0', organization_id: 'org-bayani-001', created_at: minutesAgo(20) },
  { id: 'audit-004', actor_id: 'uid-tl-001', actor_name: 'Sgt. Antonio Dela Torre', actor_role: 'team_leader', action: 'update', entity_type: 'incident', entity_id: 'inc-002', previous_values: { status: 'arrived' }, new_values: { status: 'operation_in_progress' }, ip_address: '10.0.0.5', user_agent: 'Mobile', organization_id: 'org-bayani-001', created_at: minutesAgo(15) },
  { id: 'audit-005', actor_id: 'uid-admin', actor_name: 'Ricardo Mendoza', actor_role: 'admin', action: 'login', entity_type: 'session', entity_id: null, previous_values: null, new_values: null, ip_address: '192.168.1.1', user_agent: 'Mozilla/5.0', organization_id: 'org-bayani-001', created_at: hoursAgo(1) },
  { id: 'audit-006', actor_id: 'uid-admin', actor_name: 'Ricardo Mendoza', actor_role: 'admin', action: 'update', entity_type: 'rescue_unit', entity_id: 'unit-delta', previous_values: { status: 'standby' }, new_values: { status: 'deployed' }, ip_address: '192.168.1.1', user_agent: 'Mozilla/5.0', organization_id: 'org-bayani-001', created_at: hoursAgo(2) },
  { id: 'audit-007', actor_id: null, actor_name: 'System', actor_role: 'system', action: 'create', entity_type: 'notification', entity_id: 'notif-batch-001', previous_values: null, new_values: { count: 15, type: 'daily_summary' }, ip_address: null, user_agent: null, organization_id: 'org-bayani-001', created_at: hoursAgo(6) },
  { id: 'audit-008', actor_id: 'uid-verif-001', actor_name: 'Ana Bautista', actor_role: 'verifier', action: 'update', entity_type: 'resident', entity_id: 'res-003', previous_values: { registration_status: 'pending_review' }, new_values: { registration_status: 'approved' }, ip_address: '192.168.1.11', user_agent: 'Mozilla/5.0', organization_id: 'org-bayani-001', created_at: daysAgo(1) },
]

// ============================================================
// NOTIFICATIONS
// ============================================================

export const DEMO_NOTIFICATIONS: Notification[] = [
  { id: 'notif-001', user_id: 'uid-disp', organization_id: 'org-bayani-001', title: 'New Emergency Report', message: 'Cardiac arrest reported at 12 Sampaguita St., Poblacion.', type: 'incident_new', priority: 'urgent', incident_id: 'inc-001', action_url: '/admin/incidents/inc-001', is_read: false, read_at: null, created_at: minutesAgo(25) },
  { id: 'notif-002', user_id: 'uid-tl-001', organization_id: 'org-bayani-001', title: 'Unit Assigned', message: 'Your team has been assigned to INC-2024-001001 (cardiac arrest).', type: 'incident_assigned', priority: 'urgent', incident_id: 'inc-001', action_url: '/admin/incidents/inc-001', is_read: true, read_at: minutesAgo(19), created_at: minutesAgo(20) },
  { id: 'notif-003', user_id: 'uid-res-001', organization_id: 'org-bayani-001', title: 'Rescue On the Way', message: 'Rescue Team Alpha is en route to your location. ETA 7 minutes.', type: 'incident_update', priority: 'high', incident_id: 'inc-001', action_url: '/resident/history', is_read: false, read_at: null, created_at: minutesAgo(8) },
  { id: 'notif-004', user_id: 'uid-disp', organization_id: 'org-bayani-001', title: 'Fire Report', message: 'Structure fire reported at 25 Mabini St., San Isidro.', type: 'incident_new', priority: 'high', incident_id: 'inc-002', action_url: '/admin/incidents/inc-002', is_read: true, read_at: minutesAgo(58), created_at: hoursAgo(1) },
  { id: 'notif-005', user_id: 'uid-disp', organization_id: 'org-bayani-001', title: 'Typhoon Alert', message: 'Severe typhoon damage reported in Brgy. Bagong Pag-asa. Multiple families stranded.', type: 'incident_new', priority: 'urgent', incident_id: 'inc-014', action_url: '/admin/incidents/inc-014', is_read: true, read_at: hoursAgo(7.8), created_at: hoursAgo(8) },
  { id: 'notif-006', user_id: 'uid-res-005', organization_id: 'org-bayani-001', title: 'Rescue Team Arrived', message: 'Rescue Team Charlie has arrived at your area. Evacuation underway.', type: 'incident_update', priority: 'high', incident_id: 'inc-014', action_url: '/resident/history', is_read: true, read_at: hoursAgo(5.5), created_at: hoursAgo(6) },
  { id: 'notif-007', user_id: 'uid-disp', organization_id: 'org-bayani-001', title: 'Earthquake Report', message: 'Structural damage reported at 78 Rizal Ave., Santo Niño after earthquake.', type: 'incident_new', priority: 'high', incident_id: 'inc-013', action_url: '/admin/incidents/inc-013', is_read: true, read_at: hoursAgo(2.9), created_at: hoursAgo(3) },
  { id: 'notif-008', user_id: 'uid-admin', organization_id: 'org-bayani-001', title: 'Road Cleared', message: 'Fallen tree on Chapel Road, San Jose has been removed. Road reopened.', type: 'incident_resolved', priority: 'normal', incident_id: 'inc-015', action_url: '/admin/incidents/inc-015', is_read: true, read_at: hoursAgo(6.5), created_at: hoursAgo(7) },
]

// ============================================================
// SUMMARY STATISTICS
// ============================================================

export const DEMO_STATS: DemoStats = {
  total_incidents_today: 10,
  active_incidents: 6,
  resolved_today: 3,
  average_response_time_minutes: 9.2,
  available_units: 0,
  total_units: 4,
  pending_registrations: 3,
  critical_incidents: 3,
  incidents_by_type: {
    'Earthquake': 1,
    'Typhoon / Storm': 2,
    'Medical Emergency': 3,
    'Fire': 2,
    'Vehicular Accident': 2,
    'Flood / Water Rescue': 1,
    'Missing Person': 1,
    'Crime / Security': 1,
    'Animal Rescue': 1,
    'Natural Disaster': 1,
  },
  incidents_by_status: {
    submitted: 1,
    on_the_way: 1,
    operation_in_progress: 2,
    arrived: 2,
    assigned: 1,
    verification_pending: 1,
    resolved: 3,
    closed: 2,
    false_alert: 1,
    unable_to_contact: 1,
  },
  incidents_by_severity: {
    critical: 3,
    high: 4,
    medium: 4,
    low: 2,
    info: 2,
  },
}
